"""Update all model

Revision ID: d3489e6d3eb0
Revises: 388ead4e359b
Create Date: 2025-08-31 19:48:42.682999+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3489e6d3eb0'
down_revision: Union[str, Sequence[str], None] = '388ead4e359b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genderLog', sa.Column('locationId', sa.String(length=36), nullable=False))
    op.drop_constraint(op.f('genderLog_location_fkey'), 'genderLog', type_='foreignkey')
    op.create_foreign_key(None, 'genderLog', 'location', ['locationId'], ['locationId'])
    op.drop_column('genderLog', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genderLog', sa.Column('location', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'genderLog', type_='foreignkey')
    op.create_foreign_key(op.f('genderLog_location_fkey'), 'genderLog', 'location', ['location'], ['locationId'])
    op.drop_column('genderLog', 'locationId')
    # ### end Alembic commands ###
