"""Added Gender detection model

Revision ID: f26c792616d6
Revises: 
Create Date: 2025-08-31 15:44:26.707636+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26c792616d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('cameraId', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('cameraId')
    )
    op.create_table('location',
    sa.Column('locationId', sa.String(length=36), nullable=False),
    sa.Column('cameraId', sa.String(length=36), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['cameraId'], ['camera.cameraId'], ),
    sa.PrimaryKeyConstraint('locationId')
    )
    op.create_table('genderLog',
    sa.Column('logId', sa.String(length=36), nullable=False),
    sa.Column('location', sa.String(length=36), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('detectedAt', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['location'], ['location.locationId'], ),
    sa.PrimaryKeyConstraint('logId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genderLog')
    op.drop_table('location')
    op.drop_table('camera')
    # ### end Alembic commands ###
